<#
    export-legacy-run.ps1 - stages the legacy RUN OUTPUT tables into the docker
    compare schema. Separate from export-legacy.ps1 on purpose: that one stages
    employee MASTER data, which is imported; this one stages values that are
    GENERATED by the run engine and never imported at all.

    Two families, matching the two kinds of run:

      -Kind validation   PW_T_Runf / PW_T_RunfAmts / PW_T_RunfInds
                         A what-if / validation run. The pipro counterpart is
                         payslip_core_previews (run_type = 'what_if').

      -Kind live         PW_Runf / PW_RunfAmts / PW_RunfInds
                         A final run. The pipro counterpart is payslips_core
                         plus its line tables. NOTE: a live legacy run ALSO
                         writes the run_history* family; we deliberately read
                         PW_Runf*, not history.

    NO PERIOD KEY: PW_Runf* holds only the most recent run - a new run
    overwrites it, and Pay170 clears it. The period is read from the matching
    globals row (PW_Parm_GlobalSystem for live, PW_Parm_T_GlobalSystem for
    validation) and carried as a label, so the report can show which period each
    side actually ran. These two need not agree: on the data checked, live was
    run 4 / 2026-06-30 while validation was run 5 / 2026-07-31.

    SQL Server is read with your Windows login (trusted connection). Connection
    details come from settings.local.txt.

    Usage:
      powershell -ExecutionPolicy Bypass -File export-legacy-run.ps1 -Kind live
      powershell -ExecutionPolicy Bypass -File export-legacy-run.ps1 -Kind validation
#>
param(
    [ValidateSet('live','validation')][string]$Kind = 'live',
    [string]$SqlServer,
    [string]$SqlDatabase
)
$ErrorActionPreference = 'Stop'
$here = $PSScriptRoot

. "$PSScriptRoot\load-settings.ps1"
$cfg = Import-PiproSettings
if (-not $SqlServer)   { $SqlServer   = Get-PiproSetting $cfg 'SQLSERVER' }
if (-not $SqlDatabase) { $SqlDatabase = Get-PiproSetting $cfg 'SQLSERVER_DB' }

$dockerContainer = Get-PiproSetting $cfg 'DOCKER_CONTAINER'
$dockerDb        = Get-PiproSetting $cfg 'DOCKER_DB'
$dockerUser      = Get-PiproSetting $cfg 'DOCKER_USER'
$dockerPassword  = Get-PiproSetting $cfg 'DOCKER_PASSWORD'

# PS 5.1 prepends a UTF-8 BOM when piping to a native process; COPY reads it as
# part of the first integer. Files go in via docker cp for the same reason.
$OutputEncoding = New-Object System.Text.UTF8Encoding $false

$sqlcmd = 'C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\sqlcmd.exe'
if (-not (Test-Path $sqlcmd)) { $sqlcmd = 'sqlcmd' }
$PG = @('exec','-i','-e',"PGPASSWORD=$dockerPassword",$dockerContainer,'psql','-U',$dockerUser,'-d',$dockerDb)

cmd /c "docker info >nul 2>&1"
if ($LASTEXITCODE -ne 0) {
    Write-Host "`n==> Docker is not running. Start Docker Desktop, then re-run.`n" -ForegroundColor Yellow
    exit 1
}

# The two families differ only by the T_ prefix, so one set of queries serves both.
# The globals table that describes each family follows the same convention, just
# with the prefix inside the name.
$prefix  = if ($Kind -eq 'validation') { 'PW_T_' } else { 'PW_' }
$globals = if ($Kind -eq 'validation') { 'PW_Parm_T_GlobalSystem' } else { 'PW_Parm_GlobalSystem' }

$staging = @'
CREATE SCHEMA IF NOT EXISTS compare;
DROP TABLE IF EXISTS compare.legacy_runf, compare.legacy_runf_amts, compare.legacy_runf_inds,
                     compare.legacy_run_label;
CREATE TABLE compare.legacy_runf      (kind TEXT, empno INT, payroll INT, surname TEXT,
                                       taxcode TEXT, stop_pay TEXT);
-- payroll is carried on every row because employee_code is qualified
-- "<payroll>/<EmpNo>". PW_RunfAmts/PW_RunfInds have no Payroll column of their
-- own, so it is joined in from the run header.
CREATE TABLE compare.legacy_runf_amts (kind TEXT, empno INT, payroll INT, ordinalno INT,
                                       usage_no INT, amt DOUBLE PRECISION);
CREATE TABLE compare.legacy_runf_inds (kind TEXT, empno INT, payroll INT, ordinalno INT, ind TEXT);
-- Which period the staged run belongs to. PW_Runf* carries no period itself, so
-- it is read from the globals row - and each family has its OWN globals table,
-- so no inference is needed: PW_Parm_GlobalSystem describes PW_Runf*, and
-- PW_Parm_T_GlobalSystem describes PW_T_Runf*. Label only, never compared.
-- Preferred over PW_RunH because history may not always be captured, whereas the
-- globals row always reflects the run actually sitting in the tables.
CREATE TABLE compare.legacy_run_label (kind TEXT, current_run INT,
                                       current_run_date INT, current_tax_period INT);
'@
Write-Host "==> Creating run staging tables..." -ForegroundColor Cyan
$staging | docker @PG -v ON_ERROR_STOP=on | Out-Null
if ($LASTEXITCODE -ne 0) { Write-Host "==> Staging failed." -ForegroundColor Red; exit 1 }

$extracts = @(
    @{ Table = 'compare.legacy_runf';      Cols = 'kind, empno, payroll, surname, taxcode, stop_pay';
       Query = "SELECT '$Kind', EmpNo, Payroll, ISNULL(Surname,''), ISNULL(TaxCode,''), ISNULL(StopPay,'') FROM ${prefix}Runf WHERE EmpNo > 0" },
    @{ Table = 'compare.legacy_runf_amts'; Cols = 'kind, empno, payroll, ordinalno, usage_no, amt';
       Query = "SELECT '$Kind', a.EmpNo, h.Payroll, a.OrdinalNo, a.Usage, a.Amt FROM ${prefix}RunfAmts a JOIN ${prefix}Runf h ON h.EmpNo = a.EmpNo WHERE a.EmpNo > 0" },
    @{ Table = 'compare.legacy_runf_inds'; Cols = 'kind, empno, payroll, ordinalno, ind';
       Query = "SELECT '$Kind', i.EmpNo, h.Payroll, i.OrdinalNo, ISNULL(i.Ind,'') FROM ${prefix}RunfInds i JOIN ${prefix}Runf h ON h.EmpNo = i.EmpNo WHERE i.EmpNo > 0" },
    @{ Table = 'compare.legacy_run_label'; Cols = 'kind, current_run, current_run_date, current_tax_period';
       Query = "SELECT '$Kind', CurrentRun, CurrentRunDate, CurrentTaxPeriod FROM $globals" }
)

$tmp = Join-Path $env:TEMP "pipro-legacy-run"
New-Item -ItemType Directory -Force -Path $tmp | Out-Null

foreach ($e in $extracts) {
    $name = ($e.Table -split '\.')[-1]
    $file = Join-Path $tmp "$name.psv"
    Write-Host "==> Extracting $name ($Kind)..." -ForegroundColor Cyan

    $out = & $sqlcmd -S $SqlServer -d $SqlDatabase -E -C -h -1 -W -s '|' `
                     -Q "SET NOCOUNT ON; $($e.Query)"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "==> sqlcmd failed for $name. Is SQL Server up on $SqlServer?" -ForegroundColor Red
        exit 1
    }

    $rows = $out | Where-Object { $_ -match '\S' -and $_ -notmatch '^-+(\|-+)*$' } `
                 | ForEach-Object { $_ -replace "^`u{FEFF}", '' }
    [System.IO.File]::WriteAllLines($file, $rows)
    Write-Host "    $($rows.Count) rows" -ForegroundColor DarkGray

    cmd /c "docker cp `"$file`" ${dockerContainer}:/tmp/$name.psv >nul 2>&1"
    if ($LASTEXITCODE -ne 0) { Write-Host "==> docker cp failed for $name." -ForegroundColor Red; exit 1 }

    docker exec -e PGPASSWORD=$dockerPassword $dockerContainer psql -U $dockerUser -d $dockerDb -v ON_ERROR_STOP=on `
        -c "\copy $($e.Table) ($($e.Cols)) FROM '/tmp/$name.psv' WITH (FORMAT csv, DELIMITER '|', QUOTE E'\b')" | Out-Null
    if ($LASTEXITCODE -ne 0) { Write-Host "==> COPY failed for $name." -ForegroundColor Red; exit 1 }
}

Write-Host "`n==> Staged the $Kind run. Canonicalise and diff it with run_report.cmd $Kind" -ForegroundColor Green
