@echo off
rem ===========================================================================
rem  run_report.cmd - READ-ONLY comparison of RUN OUTPUT: legacy SQL Server
rem  against the experimental Postgres.
rem
rem  Usage:  run_report.cmd [live^|validation] [period_id]
rem          defaults: live, and the period of the LATEST EXPERIMENTAL RUN
rem
rem  HOW THIS DIFFERS FROM compare_report.cmd: that one checks employee MASTER
rem  data, which is imported, so a difference there is an import defect. This
rem  checks values GENERATED by the two run engines, so a difference here is the
rem  engines disagreeing. Run the import report first - if the inputs differ,
rem  the outputs are guaranteed to, and this report will say so and stop.
rem
rem  WHICH LEGACY TABLES
rem     live        PW_Runf*    a final run   (also writes run_history*, ignored)
rem     validation  PW_T_Runf*  a what-if run
rem
rem  PW_Runf* HAS NO PERIOD KEY - it holds only the most recent run, which may be
rem  a different period from the pipro run being compared. Section 0 of the report
rem  prints the period and date BOTH sides actually ran, so a wall of differences
rem  can be read as a period mismatch rather than an engine fault. For a live run
rem  the legacy period is recovered from PW_RunH; a validation run records none.
rem
rem  Writes only to the compare schema. Each step pauses - Ctrl+C to abort.
rem ===========================================================================
setlocal
cd /d "%~dp0"

set KIND=%~1
if not defined KIND set KIND=live
if /i not "%KIND%"=="live" if /i not "%KIND%"=="validation" (
    echo     Usage: run_report.cmd [live^|validation] [period_id]
    exit /b 1
)

if not exist "settings.local.txt" (
    echo.
    echo     No settings.local.txt found in this folder.
    echo     Copy settings.example.txt to settings.local.txt and fill in your own
    echo     database details - it is gitignored, so it stays on your machine.
    goto :failed
)
for /f "usebackq eol=# tokens=1,* delims==" %%a in ("settings.local.txt") do set "%%a=%%b"

set TENANT=%TENANT_SCHEMA%
set SOURCE=%INTERIM_SCHEMA%
set PSQL=docker exec -i -e PGPASSWORD=%DOCKER_PASSWORD% %DOCKER_CONTAINER% psql -U %DOCKER_USER% -d %DOCKER_DB% -v ON_ERROR_STOP=on
if not defined TENANT goto :nosetting

docker info >nul 2>&1
if errorlevel 1 (
    echo     Docker is not running. Start Docker Desktop and re-run.
    goto :failed
)

rem Period: the argument wins if given. The query result is written to a file and
rem read back because cmd splits on the '=' in "-e PGPASSWORD=..." when a command
rem string is parsed inside for/f.
set PERIOD=%~2
if not defined PERIOD (
    rem The period of the LATEST EXPERIMENTAL RUN, not the latest period by date:
    rem the newest period is usually an empty future one, and the point of this
    rem report is to compare runs that actually happened. Ordered by the run's own
    rem finish time; falls back to the latest period that has any output, then to
    rem the latest period. Never ordered by period id - this tenant's July is id 1
    rem with later ids on earlier months.
    %PSQL% -t -A -c "SELECT COALESCE((SELECT r.period_id FROM %TENANT%.payroll_runs r ORDER BY r.finished_at DESC NULLS LAST, r.id DESC LIMIT 1), (SELECT p.id FROM %TENANT%.payroll_periods p WHERE EXISTS (SELECT 1 FROM %TENANT%.payslips_core s WHERE s.period_id = p.id) OR EXISTS (SELECT 1 FROM %TENANT%.payslip_core_previews v WHERE v.period_id = p.id) ORDER BY p.period_end DESC, p.id DESC LIMIT 1), (SELECT p.id FROM %TENANT%.payroll_periods p ORDER BY p.period_end DESC, p.id DESC LIMIT 1))" > "%TEMP%\pipro-period.txt"
    if errorlevel 1 goto :failed
    for /f "usebackq delims= " %%p in ("%TEMP%\pipro-period.txt") do set PERIOD=%%p
    del "%TEMP%\pipro-period.txt" >nul 2>&1
)
if not defined PERIOD (
    echo     Could not determine a pipro period. Pass one: run_report.cmd %KIND% ^<period_id^>
    goto :failed
)

echo.
echo ===========================================================================
echo  RUN REPORT   kind: %KIND%   pipro period: %PERIOD%      (read-only)
echo  Tenant : %TENANT%
echo ===========================================================================

rem --- Step 1 -----------------------------------------------------------------
echo.
echo [1/4] Stage the legacy run output.
echo       %KIND% run - reading PW_Runf* / PW_T_Runf*, NOT run_history*.
echo       Remember this is whatever run is currently sitting in those tables.
echo.
powershell -ExecutionPolicy Bypass -File .\export-legacy-run.ps1 -Kind %KIND%
if errorlevel 1 goto :failed
pause

rem --- Step 2 -----------------------------------------------------------------
echo.
echo [2/4] Canonicalise the legacy side.
echo.
type sql\95_run_snapshot.sql | %PSQL% -v snap=legacy-run-%KIND% -v system=legacy -v kind=%KIND% -v tenant_schema=%TENANT% -v period_id=%PERIOD%
if errorlevel 1 goto :failed
pause

rem --- Step 3 -----------------------------------------------------------------
echo.
echo [3/4] Canonicalise the experimental side.
echo       A what-if run stores only totals, so line_values may legitimately be 0.
echo.
type sql\95_run_snapshot.sql | %PSQL% -v snap=pipro-run-%KIND% -v system=pipro -v kind=%KIND% -v tenant_schema=%TENANT% -v period_id=%PERIOD%
if errorlevel 1 goto :failed
pause

rem --- Step 4 -----------------------------------------------------------------
echo.
echo [4/4] Diff, with the noise gates applied.
echo       Read section 0 first - it says which gate fired and why, and that
echo       decides how much of the rest is shown.
echo.
type sql\96_run_diff.sql | %PSQL% -v a=legacy-run-%KIND% -v b=pipro-run-%KIND% -v master_a=legacy-before -v master_b=pipro-before -v tolerance=10
if errorlevel 1 goto :failed

echo.
echo ===========================================================================
echo  Run report finished. Nothing outside the compare schema was modified.
echo ===========================================================================
pause
exit /b 0

:nosetting
echo.
echo     settings.local.txt is missing TENANT_SCHEMA.
echo     See settings.example.txt for the full list.
goto :failed

:failed
echo.
echo ===========================================================================
echo  FAILED on the step above. Nothing further has run.
echo  No legacy, interim or tenant data was modified by this script.
echo ===========================================================================
pause
exit /b 1
