-- ===========================================================================
-- 50_legacy_carry_company.sql — interim COMPANY-schema tables
-- GENERATED by tools/generate-carry.js — edit the generator, not this file.
-- Run ONCE PER TENANT after 10_employees.sql (employee ids must exist).
-- Runner variables: :legacy_schema :tenant_schema :payroll_number
--
-- Source identifiers are UNQUOTED LOWERCASE: DataDictionary's ColumnCollection
-- lowercases every table/column name, so that is what the desktop DB contains.
-- ===========================================================================
\set ON_ERROR_STOP on
BEGIN;
SET search_path TO :"tenant_schema", public;

-- ---- settings_bank_transfer ----
INSERT INTO settings_bank_transfer (transfer_no, amount_format_no_dec, batch_auto_update, batch_no, beneficiary_ref, co_accno, co_bankname, co_branchcode, co_statement_ref, date_format, eft_name, file_format, has_1_header_record, has_2_detail_record, has_3_trailer_record, has_4_contra_record, split_pay_code, thirdpartypay_transfer, transfer_descr)
SELECT s.transfer_no, s.amount_format_no_dec, s.batch_auto_update, s.batch_no, s.beneficiary_ref, s.co_accno, s.co_bankname, s.co_branchcode, s.co_statement_ref, s.date_format, s.eft_name, s.file_format, s.has_1_header_record, s.has_2_detail_record, s.has_3_trailer_record, s.has_4_contra_record, s.split_pay_code, s.thirdpartypay_transfer, s.transfer_descr
FROM :"legacy_schema".settings_bank_transfer s
ON CONFLICT (transfer_no) DO NOTHING;

-- ---- settings_bank_transfer_value ----
INSERT INTO settings_bank_transfer_value (transfer_no, record_type, ordinal_no, field_length, field_position, literal_value, opa, opn)
SELECT s.transfer_no, s.record_type, s.ordinalno, s.field_length, s.field_position, s.literal_value, s.opa, s.opn
FROM :"legacy_schema".settings_bank_transfer_value s
ON CONFLICT (transfer_no, record_type, ordinal_no) DO NOTHING;

-- ---- settings_currency ----
INSERT INTO settings_currency (payroll, country_code, currency_code1, currency_code2, currency_exchange, currency_exchange_buy, currency_exchange_sell, tax_currency_code)
SELECT s.payroll, s.country_code, s.currency_code1, s.currency_code2, s.currency_exchange, s.currency_exchange_buy, s.currency_exchange_sell, s.tax_currency_code
FROM :"legacy_schema".settings_currency s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_user ----
INSERT INTO settings_user (payroll, allow_future_eng_dates, bank_tfr_ind, batch_hash_tot, batch_no_auto_disp_ind, batch_no_auto_ind, batch_totals_ind, batch_tot_amts, batch_tot_chk_digit, batch_tot_code, batch_tot_empno, batch_tot_rate, batch_tot_rate_amt, check_leave_dates, decimal_reduction_ind, emp_exclnd_value, emp_perm_ind_value, emp_status_ind_no, emp_temp_ind_value, ext_rate_code_a, ext_rate_code_n, force_leave_date_capture, header, increment_ord, interest_ind, leave_system_ind, lve_calc_iteration, man_calc_iteration, min_age_employment, multi_cost_ind, multi_rate_ind, part_pay_ind, pay_reversal_ind, prod_bonus_global_tbl, prt_surname_on_exception, rate_limit, rev_calc_iteration, ru_advance_code, ru_amount, ru_recovery_code, standard_hrs_code, stop_pay, tran_entry_date_ind, tranf_cost_codes_flag, decimal_separator, thousand_separator, amount_length, amount_decimals, positive_sign, negative_sign, leading_sign, paper_size, landscape, point_size_base, point_size_bold, border_horizontal, border_vertical, leave_holiday_yr_start)
SELECT s.payroll, s.allowfutureengdates, s.banktfrind, s.batchhashtot, s.batchnoautodispind, s.batchnoautoind, s.batchtotalsind, s.batchtotamts, s.batchtotchkdigit, s.batchtotcode, s.batchtotempno, s.batchtotrate, s.batchtotrateamt, s.checkleavedates, s.decimalreductionind, s.empexclndvalue, s.emppermindvalue, s.empstatusindno, s.emptempindvalue, s.extratecodea, s.extratecoden, s.forceleavedatecapture, s.header, s.incrementord, s.interestind, s.leavesystemind, s.lvecalciteration, s.mancalciteration, s.minageemployment, s.multicostind, s.multirateind, s.partpayind, s.payreversalind, s.prodbonusglobaltbl, s.prtsurnameonexception, s.ratelimit, s.revcalciteration, s.ruadvancecode, s.ruamount, s.rurecoverycode, s.standardhrscode, s.stoppay, s.tranentrydateind, s.tranfcostcodesflag, s.decimal_separator, s.thousand_separator, s.amount_length, s.amount_decimals, s.positive_sign, s.negative_sign, s.leading_sign, s.paper_size, s.landscape, s.point_size_base, s.point_size_bold, s.border_horizontal, s.border_vertical, s.leave_holiday_yr_start
FROM :"legacy_schema".settings_user s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_global ----
INSERT INTO settings_global (payroll, adjust_run_count, consol_cost_flag, consol_flag, current_iteration, current_run, current_run_date, current_tax_period, include3rd_party_trans, include_batch_mastf, include_batch_trans, include_delay_trans, include_man_pays, include_other_trans, include_permtrans, interim_payroll, interim_tax_to_date, interim_tax_to_period, permit_costing_flag, system_date, zero_runf_flag, vat_percentage, take_on_ind, trans_seq_no)
SELECT s.payroll, s.adjustruncount, s.consolcostflag, s.consolflag, s.currentiteration, s.currentrun, s.currentrundate, s.currenttaxperiod, s.include3rdpartytrans, s.includebatchmastf, s.includebatchtrans, s.includedelaytrans, s.includemanpays, s.includeothertrans, s.includepermtrans, s.interimpayroll, s.interimtaxtodate, s.interimtaxtoperiod, s.permitcostingflag, s.systemdate, s.zerorunfflag, s.vatpercentage, s.takeonind, s.transseqno
FROM :"legacy_schema".settings_global s
ON CONFLICT (payroll) DO NOTHING;

-- ---- employee_increments ----
INSERT INTO employee_increments (id, employee_id, date_d8, amount_u)
SELECT s.autonumber, e.user_id, s.date_d8, s.amount_u
FROM :"legacy_schema".employee_increments s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('employee_increments', 'id'), (SELECT COALESCE(MAX(id), 0) + 1 FROM employee_increments), false);

-- ---- settings_thirdparty_codes ----
INSERT INTO settings_thirdparty_codes (ordinal_no, balance_code, ded_type, delete_flag, transaction_code)
SELECT s.ordinalno, s.balancecode, s.dedtype, s.deleteflag, s.transactioncode
FROM :"legacy_schema".settings_thirdparty_codes s
ON CONFLICT (ordinal_no) DO NOTHING;

-- ---- settings_thirdparty_dedtype ----
INSERT INTO settings_thirdparty_dedtype (ded_type, ded_description)
SELECT s.dedtype, s.deddescription
FROM :"legacy_schema".settings_thirdparty_dedtype s
ON CONFLICT (ded_type) DO NOTHING;

-- ---- settings_thirdparty_agents ----
INSERT INTO settings_thirdparty_agents (agent_key, address1, address2, address3, address4, agent_name, bank_account_name, bank_account_number, bank_account_type, branch_code, email_address, pay_mode, phone_number, post_code)
SELECT s.agentkey, s.address1, s.address2, s.address3, s.address4, s.agentname, s.bankaccountname, s.bankaccountnumber, s.bankaccounttype, s.branchcode, s.emailaddress, s.paymode, s.phonenumber, s.postcode
FROM :"legacy_schema".settings_thirdparty_agents s
ON CONFLICT (agent_key) DO NOTHING;

-- ---- settings_thirdparty_eft ----
INSERT INTO settings_thirdparty_eft (agent_key, ordinal_no, agent_name, bank_acc_name, bank_acc_no, bank_acc_type, bank_name, branch_code, branch_name, reference_no, total_amount)
SELECT s.agentkey, s.ordinalno, s.agentname, s.bankaccname, s.bankaccno, s.bankacctype, s.bankname, s.branchcode, s.branchname, s.referenceno, s.totalamount
FROM :"legacy_schema".settings_thirdparty_eft s
ON CONFLICT (agent_key, ordinal_no) DO NOTHING;

-- ---- employee_thirdparty_transact ----
INSERT INTO employee_thirdparty_transact (employee_id, trans_seq_no, amount, class_no, code, cost_code, date_value, user_id)
SELECT e.user_id, s.transseqno, s.amount, s.classno, s.code, s.costcode, s.datevalue, s.user_id
FROM :"legacy_schema".employee_thirdparty_transact s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (employee_id, trans_seq_no) DO NOTHING;

-- ---- settings_banks ----
INSERT INTO settings_banks (branch_code, bank_name, branch_addr1, branch_addr2, branch_addr3, branch_addr4, branch_name, country_code, bank_swift_code)
SELECT s.branchcode, s.bankname, s.branchaddr1, s.branchaddr2, s.branchaddr3, s.branchaddr4, s.branchname, s.countrycode, s.bankswiftcode
FROM :"legacy_schema".settings_banks s
ON CONFLICT (branch_code) DO NOTHING;

-- ---- employee_leave_history ----
INSERT INTO employee_leave_history (id, employee_id, code, leave_type, from_date, to_date, duration, remarks)
SELECT s.autonumber, e.user_id, s.code, s.leavetype, s.fromdate, s.todate, s.duration, s.remarks
FROM :"legacy_schema".employee_leave_history s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('employee_leave_history', 'id'), (SELECT COALESCE(MAX(id), 0) + 1 FROM employee_leave_history), false);

-- ---- settings_costcode_breaks ----
INSERT INTO settings_costcode_breaks (payroll, break_no, ordinal_no, break_code, break_desc)
SELECT s.payroll, s.breakno, s.ordinalno, s.breakcode, s.breakdesc
FROM :"legacy_schema".settings_costcode_breaks s
ON CONFLICT (payroll, break_no, ordinal_no) DO NOTHING;

-- ---- settings_costing_general ----
INSERT INTO settings_costing_general (company_id, averaging_override, cost_code_mask, proportional_code)
SELECT s.company_id, s.averagingoverride, s.costcodemask, s.proportionalcode
FROM :"legacy_schema".settings_costing_general s
ON CONFLICT (company_id) DO NOTHING;

-- ---- settings_company_third_party ----
INSERT INTO settings_company_third_party (company_id, company_account, ee_contrib_code, ee_ind_no, ee_ref_no, er_contrib_code, payment_ref, pay_mode, text_file_name)
SELECT s.company_id, s.company_account, s.eecontribcode, s.eeindno, s.eerefno, s.ercontribcode, s.paymentref, s.paymode, s.textfilename
FROM :"legacy_schema".settings_company_third_party s
ON CONFLICT (company_id) DO NOTHING;

-- ---- settings_report ----
INSERT INTO settings_report (payroll, report_no, alpha_delimiter, blank_lines_after_detail, blank_lines_after_head, dont_print_pay_hdr, ee_count, ee_count_total_id, ee_new_page, extract_headers, extract_incl_break_vals, extract_rec_type, extract_totals, file_name, final_totals, final_totals_legend, final_totals_new_page, hist_date_opt, hist_fix_end_date, hist_fix_start_date, hist_incl_h_head, hist_months, hist_period_opt, hist_report, hist_st_end_opt, hist_year_opt, include_manual_payments, include_run_data, include_zero_pay_current_e_es, include_zero_pay_terminations, no_of_detail_lines, no_of_heading_lines, no_of_total_lines, paper_size, print_orientation, report_name, sign_negative, sign_pos, sign_positive, space_fill_zero_details, space_fill_zero_totals, summary_report, suppress_zero_lines, use_alt_descr, watermark)
SELECT s.payroll, s.reportno, s.alphadelimiter, s.blanklinesafterdetail, s.blanklinesafterhead, s.dontprintpayhdr, s.eecount, s.eecounttotalid, s.eenewpage, s.extractheaders, s.extractinclbreakvals, s.extractrectype, s.extracttotals, s.filename, s.finaltotals, s.finaltotalslegend, s.finaltotalsnewpage, s.histdateopt, s.histfixenddate, s.histfixstartdate, s.histinclhhead, s.histmonths, s.histperiodopt, s.histreport, s.histstendopt, s.histyearopt, s.includemanualpayments, s.includerundata, s.includezeropaycurrentees, s.includezeropayterminations, s.noofdetaillines, s.noofheadinglines, s.nooftotallines, s.papersize, s.printorientation, s.reportname, s.signnegative, s.signpos, s.signpositive, s.spacefillzerodetails, s.spacefillzerototals, s.summaryreport, s.suppresszerolines, s.usealtdescr, s.watermark
FROM :"legacy_schema".settings_report s
ON CONFLICT (payroll, report_no) DO NOTHING;

-- ---- settings_report_breaks ----
INSERT INTO settings_report_breaks (payroll, report_no, break_set, ordinal_no, break_flag, break_interpret, key_end, key_start, legend, new_page, opa, op_n)
SELECT s.payroll, s.reportno, s.breakset, s.ordinalno, s.breakflag, s.breakinterpret, s.keyend, s.keystart, s.legend, s.newpage, s.opa, s.opn
FROM :"legacy_schema".settings_report_breaks s
ON CONFLICT (payroll, report_no, break_set, ordinal_no) DO NOTHING;

-- ---- settings_report_calcs ----
INSERT INTO settings_report_calcs (payroll, report_no, ordinal_no, calc_time, ind_no, ind_val, op1_a, op1_n, op2_a, op2_n, op3_a, op3_n, op_code)
SELECT s.payroll, s.reportno, s.ordinalno, s.calctime, s.indno, s.indval, s.op1a, s.op1n, s.op2a, s.op2n, s.op3a, s.op3n, s.opcode
FROM :"legacy_schema".settings_report_calcs s
ON CONFLICT (payroll, report_no, ordinal_no) DO NOTHING;

-- ---- settings_report_details ----
INSERT INTO settings_report_details (payroll, report_no, ordinal_no, alt_descr, description, edit_option, extract_as_credit, extract_line_split, extract_to_file, length, line_no, literal, op_a, op_n, print_pos, rep_literal, signed, suppress_if_blank, total, total_id)
SELECT s.payroll, s.reportno, s.ordinalno, s.altdescr, s.description, s.editoption, s.extractascredit, s.extractlinesplit, s.extracttofile, s.length, s.lineno, s.literal, s.opa, s.opn, s.printpos, s.repliteral, s.signed, s.suppressifblank, s.total, s.totalid
FROM :"legacy_schema".settings_report_details s
ON CONFLICT (payroll, report_no, ordinal_no) DO NOTHING;

-- ---- settings_report_headings ----
INSERT INTO settings_report_headings (payroll, report_no, ordinal_no, extract_to_file, heading, length, line_no, print_pos, rep_literal)
SELECT s.payroll, s.reportno, s.ordinalno, s.extracttofile, s.heading, s.length, s.lineno, s.printpos, s.repliteral
FROM :"legacy_schema".settings_report_headings s
ON CONFLICT (payroll, report_no, ordinal_no) DO NOTHING;

-- ---- settings_report_history ----
INSERT INTO settings_report_history (payroll, report_no, ordinal_no, description)
SELECT s.payroll, s.reportno, s.ordinalno, s.description
FROM :"legacy_schema".settings_report_history s
ON CONFLICT (payroll, report_no, ordinal_no) DO NOTHING;

-- ---- settings_report_variables ----
INSERT INTO settings_report_variables (payroll, template_no, link_ord_no, var_type, description, line_no, opa, op_n, text_value)
SELECT s.payroll, s.templateno, s.linkordno, s.vartype, s.description, s.lineno, s.opa, s.opn, s.textvalue
FROM :"legacy_schema".settings_report_variables s
ON CONFLICT (payroll, template_no, link_ord_no, var_type) DO NOTHING;

-- ---- settings_report_totald ----
INSERT INTO settings_report_totald (payroll, report_no, ordinal_no, description)
SELECT s.payroll, s.reportno, s.ordinalno, s.description
FROM :"legacy_schema".settings_report_totald s
ON CONFLICT (payroll, report_no, ordinal_no) DO NOTHING;

-- ---- settings_report_totals ----
INSERT INTO settings_report_totals (payroll, report_no, ordinal_no, alt_descr, break_legend, break_val, edit_option, extract_as_credit, extract_line_split, extract_to_file, length, line_no, literal, print_pos, rep_literal, signed, total_id)
SELECT s.payroll, s.reportno, s.ordinalno, s.altdescr, s.breaklegend, s.breakval, s.editoption, s.extractascredit, s.extractlinesplit, s.extracttofile, s.length, s.lineno, s.literal, s.printpos, s.repliteral, s.signed, s.totalid
FROM :"legacy_schema".settings_report_totals s
ON CONFLICT (payroll, report_no, ordinal_no) DO NOTHING;

-- ---- settings_report_storage ----
INSERT INTO settings_report_storage (payroll, report_no, ordinal_no, data_type, default_value, description)
SELECT s.payroll, s.reportno, s.ordinalno, s.datatype, s.defaultvalue, s.description
FROM :"legacy_schema".settings_report_storage s
ON CONFLICT (payroll, report_no, ordinal_no) DO NOTHING;

-- ---- settings_leave_details ----
INSERT INTO settings_leave_details (ordinal_no, leave_balance_code, leave_desc, leave_entitle_code, leave_liability_code, leave_taken_code, leave_type)
SELECT s.ordinalno, s.leavebalancecode, s.leavedesc, s.leaveentitlecode, s.leaveliabilitycode, s.leavetakencode, s.leavetype
FROM :"legacy_schema".settings_leave_details s
ON CONFLICT (ordinal_no) DO NOTHING;

-- ---- settings_leave_history_report ----
INSERT INTO settings_leave_history_report (report_no, duration, end_date, end_emp_no, ext_leave_vals_type_b, file_path_name, include_dis, new_page_ee, new_page_type, no_breaks, report_name, sick_leave_accr_code, sick_leave_cycle_code, sick_leave_start_date_code, sick_leave_type, start_date, start_emp_no)
SELECT s.reportno, s.duration, s.enddate, s.endempno, s.extleavevalstypeb, s.filepathname, s.includedis, s.newpageee, s.newpagetype, s.nobreaks, s.reportname, s.sickleaveaccrcode, s.sickleavecyclecode, s.sickleavestartdatecode, s.sickleavetype, s.startdate, s.startempno
FROM :"legacy_schema".settings_leave_history_report s
ON CONFLICT (report_no) DO NOTHING;

-- ---- settings_leave_history_report_breaks ----
INSERT INTO settings_leave_history_report_breaks (report_no, ordinal_no, break_legend, key_end, key_start, new_page_ind)
SELECT s.reportno, s.ordinalno, s.breaklegend, s.keyend, s.keystart, s.newpageind
FROM :"legacy_schema".settings_leave_history_report_breaks s
ON CONFLICT (report_no, ordinal_no) DO NOTHING;

-- ---- settings_leave_history_report_type ----
INSERT INTO settings_leave_history_report_type (report_no, ordinal_no, leave_type)
SELECT s.reportno, s.ordinalno, s.leavetype
FROM :"legacy_schema".settings_leave_history_report_type s
ON CONFLICT (report_no, ordinal_no) DO NOTHING;

-- ---- settings_payslip ----
INSERT INTO settings_payslip (company_id, bank_acc_no_ind, bank_name_ind, co_address1, co_address2, co_address3, co_address4, co_address_code, co_address_in_footer, dependant_rebate, first_names_flag, form_length, hide_deductions, hide_statistics, incl_messages, leave_accum, leave_bal, leave_days, multi_pages_payslips, payslip_layout, print_tax_period, rate_a, rate_n, rate_dop_a, rate_d_op_n, rate_hop_a, rate_h_op_n, rate_mop_a, rate_m_op_n, remittance_flag, suppress_totals, totals_flag, tot_co_exp_code, tot_co_exp_code_ytd, use_address_flag, user_name, user_name2, a_op_description, r_op_description, u_op_description, v_op_description)
SELECT s.company_id, s.bankaccnoind, s.banknameind, s.coaddress1, s.coaddress2, s.coaddress3, s.coaddress4, s.coaddresscode, s.coaddressinfooter, s.dependantrebate, s.firstnamesflag, s.formlength, s.hidedeductions, s.hidestatistics, s.inclmessages, s.leave_accum, s.leave_bal, s.leave_days, s.multipagespayslips, s.paysliplayout, s.printtaxperiod, s.ratea, s.raten, s.ratedopa, s.ratedopn, s.ratehopa, s.ratehopn, s.ratemopa, s.ratemopn, s.remittanceflag, s.suppresstotals, s.totalsflag, s.totcoexpcode, s.totcoexpcodeytd, s.useaddressflag, s.username, s.username2, s.aopdescription, s.ropdescription, s.uopdescription, s.vopdescription
FROM :"legacy_schema".settings_payslip s
ON CONFLICT (company_id) DO NOTHING;

-- ---- settings_payslip_amounts ----
INSERT INTO settings_payslip_amounts (ordinal_no, a_col, a_row, aop_a, a_op_n, rop_a, r_op_n, uop_a, u_op_n, vop_a, v_op_n)
SELECT s.ordinalno, s.acol, s.arow, s.aopa, s.aopn, s.ropa, s.ropn, s.uopa, s.uopn, s.vopa, s.vopn
FROM :"legacy_schema".settings_payslip_amounts s
ON CONFLICT (ordinal_no) DO NOTHING;

-- ---- settings_payslip_descript ----
INSERT INTO settings_payslip_descript (ordinal_no, d_col, d_row, description)
SELECT s.ordinalno, s.dcol, s.drow, s.description
FROM :"legacy_schema".settings_payslip_descript s
ON CONFLICT (ordinal_no) DO NOTHING;

-- ---- settings_payslip_message ----
INSERT INTO settings_payslip_message (ordinal_no, message)
SELECT s.ordinalno, s.message
FROM :"legacy_schema".settings_payslip_message s
ON CONFLICT (ordinal_no) DO NOTHING;

-- ---- settings_payslip_user ----
INSERT INTO settings_payslip_user (ordinal_no, user_descr, user_field, user_literal, user_occur)
SELECT s.ordinalno, s.userdescr, s.userfield, s.userliteral, s.useroccur
FROM :"legacy_schema".settings_payslip_user s
ON CONFLICT (ordinal_no) DO NOTHING;

-- ---- settings_split_payment_code ----
INSERT INTO settings_split_payment_code (split_pay_code)
SELECT s.splitpaycode
FROM :"legacy_schema".settings_split_payment_code s
ON CONFLICT (split_pay_code) DO NOTHING;

-- ---- settings_tax_certificate_bwa_botswana ----
INSERT INTO settings_tax_certificate_bwa_botswana (payroll, employment_ref, heading1, heading2, heading3, heading4, heading5)
SELECT s.payroll, s.employmentref, s.heading1, s.heading2, s.heading3, s.heading4, s.heading5
FROM :"legacy_schema".settings_tax_certificate_bwa_botswana s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_tax_certificate_bwa_blocks ----
INSERT INTO settings_tax_certificate_bwa_blocks (payroll, ordinal_no, block_description)
SELECT s.payroll, s.ordinalno, s.blockdescription
FROM :"legacy_schema".settings_tax_certificate_bwa_blocks s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_tax_certificate_bwa_calcs ----
INSERT INTO settings_tax_certificate_bwa_calcs (payroll, ordinal_no, op1_a, op1_n, op2_n, op_code)
SELECT s.payroll, s.ordinalno, s.op1a, s.op1n, s.op2n, s.opcode
FROM :"legacy_schema".settings_tax_certificate_bwa_calcs s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_tax_certificate_lso_lesotho ----
INSERT INTO settings_tax_certificate_lso_lesotho (payroll, co_cc_end, co_cc_start, designation, status_divorced, marital_status_ind, status_married, status_single, status_widowed, multi_co_ind, spouse_name_ref_no, tax_ded_code)
SELECT s.payroll, s.coccend, s.coccstart, s.designation, s.statusdivorced, s.maritalstatusind, s.statusmarried, s.statussingle, s.statuswidowed, s.multicoind, s.spousenamerefno, s.taxdedcode
FROM :"legacy_schema".settings_tax_certificate_lso_lesotho s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_tax_certificate_lso_calcs ----
INSERT INTO settings_tax_certificate_lso_calcs (payroll, ordinal_no, op1_a, op1_n, op2_n, op_code)
SELECT s.payroll, s.ordinalno, s.op1a, s.op1n, s.op2n, s.opcode
FROM :"legacy_schema".settings_tax_certificate_lso_calcs s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_tax_certificate_swz_calcs ----
INSERT INTO settings_tax_certificate_swz_calcs (payroll, ordinal_no, op1_a, op1_n, op2_a, op2_n, op_code)
SELECT s.payroll, s.ordinalno, s.op1a, s.op1n, s.op2a, s.op2n, s.opcode
FROM :"legacy_schema".settings_tax_certificate_swz_calcs s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_tax_certificate_swz_header ----
INSERT INTO settings_tax_certificate_swz_header (payroll, ordinal_no, heading)
SELECT s.payroll, s.ordinalno, s.heading
FROM :"legacy_schema".settings_tax_certificate_swz_header s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_tax_certificate_swz_eswatini ----
INSERT INTO settings_tax_certificate_swz_eswatini (payroll, class_ind_no, grade_tax_numberopa, grade_tax_number_op_n)
SELECT s.payroll, s.classindno, s.gradetaxnumberopa, s.gradetaxnumberopn
FROM :"legacy_schema".settings_tax_certificate_swz_eswatini s
ON CONFLICT (payroll) DO NOTHING;

-- ---- equity ----
INSERT INTO equity (id, employee_id, code, date_value, details, occ_cat, occ_lev)
SELECT s.autonumber, e.user_id, s.code, s.datevalue, s.details, s.occcat, s.occlev
FROM :"legacy_schema".equity s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('equity', 'id'), (SELECT COALESCE(MAX(id), 0) + 1 FROM equity), false);

-- ---- employment_tax_incentive ----
INSERT INTO employment_tax_incentive (eti_year, period_no, employee_id, eti_claim, eti_hours, eti_ind_val, eti_wage_paid, monthly_min_wage, mtdeti_gross, mtd_gross)
SELECT s.etiyear, s.periodno, e.user_id, s.eticlaim, s.etihours, s.etiindval, s.etiwagepaid, s.monthlyminwage, s.mtdetigross, s.mtdgross
FROM :"legacy_schema".employment_tax_incentive s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (eti_year, period_no, employee_id) DO NOTHING;

-- ---- fund_mibfa ----
INSERT INTO fund_mibfa (company_id, employee_id, birth_date, new_birth_date, comment, discharge_date, engage_date, new_engage_date, id_no, new_id_no, leave_enhance_pay, name, new_name, no_shifts, no_weeks_work, pay_rate, new_pay_rate, pens_salary, trade_union, new_trade_union, wage_cat)
SELECT s.company_id, e.user_id, s.birthdate, s.newbirthdate, s.comment, s.dischargedate, s.engagedate, s.newengagedate, s.idno, s.newidno, s.leaveenhancepay, s.name, s.newname, s.noshifts, s.noweekswork, s.payrate, s.newpayrate, s.penssalary, s.tradeunion, s.newtradeunion, s.wagecat
FROM :"legacy_schema".fund_mibfa s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (company_id, employee_id) DO NOTHING;

-- ---- fund_mibfa_header ----
INSERT INTO fund_mibfa_header (ordinal_no, run_no)
SELECT s.ordinalno, s.runno
FROM :"legacy_schema".fund_mibfa_header s
ON CONFLICT (ordinal_no) DO NOTHING;

-- ---- fund_mibfa_other ----
INSERT INTO fund_mibfa_other (company_id, employee_id, ordinal_no, apprentice, coll_barg_ee, coll_barg_er, dispute_ee, dispute_er, pen_ee, pen_er, pension, pen_vol_ee, pen_vol_er, prov_ee, prov_er, provident, prov_vol_ee, prov_vol_er, sched_cont_ee, sched_cont_er, schedule_ee, sick, sick_ee, sick_er, tech_fund, technology, temp_ee)
SELECT s.company_id, e.user_id, s.ordinalno, s.apprentice, s.collbargee, s.collbarger, s.disputeee, s.disputeer, s.penee, s.pener, s.pension, s.penvolee, s.penvoler, s.provee, s.prover, s.provident, s.provvolee, s.provvoler, s.schedcontee, s.schedconter, s.scheduleee, s.sick, s.sickee, s.sicker, s.techfund, s.technology, s.tempee
FROM :"legacy_schema".fund_mibfa_other s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (company_id, employee_id, ordinal_no) DO NOTHING;

-- ---- settings_apso_tax_codes ----
INSERT INTO settings_apso_tax_codes (payroll, ordinal_no, time_code)
SELECT s.payroll, s.ordinalno, s.timecode
FROM :"legacy_schema".settings_apso_tax_codes s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_equity ----
INSERT INTO settings_equity (payroll, average_remuneration_code, disable_ind, ethnic_grp_ind, fixed_remuneration_code, foreign_ind, function_ind, high_remuneration_code, income_diff_code, low_remuneration_code, median_remuneration_code, occ_cat_ind, occ_lev_ind, perm_temp_ind, statutory_entity, term_code_ind, total_remuneration_code, variable_remuneration_code)
SELECT s.payroll, s.averageremunerationcode, s.disableind, s.ethnicgrpind, s.fixedremunerationcode, s.foreignind, s.functionind, s.highremunerationcode, s.incomediffcode, s.lowremunerationcode, s.medianremunerationcode, s.occcatind, s.occlevind, s.permtempind, s.statutoryentity, s.termcodeind, s.totalremunerationcode, s.variableremunerationcode
FROM :"legacy_schema".settings_equity s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_zaf_uif_calcs ----
INSERT INTO settings_zaf_uif_calcs (payroll, ordinal_no, op1_a, op1_n, op2_n, op_code)
SELECT s.payroll, s.ordinalno, s.op1a, s.op1n, s.op2n, s.opcode
FROM :"legacy_schema".settings_zaf_uif_calcs s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_zaf_uif ----
INSERT INTO settings_zaf_uif (payroll, uif_year, uif_month, uif_time_stamp, bank_acc_type_ind, earnings_uif_code, ee_percent_reg, employ_status_code, er_percent_reg, extendible_int_file_ind, multi_uif_co_ind, other_noopa, other_no_op_n, reason_non_contrib_code, uifcc_file_path, uif_co_code_end, uif_co_code_start, uif_co_no, uif_co_odbc, uif_country_ind, uifee_contrib_code, uifer_contrib_code, uif_file_no, uif_file_odbc, uif_grs_tax_remun_code, uif_interim_file_path, uif_limit_reg, uif_monthly_limit)
SELECT s.payroll, s.uifyear, s.uifmonth, s.uiftimestamp, s.bankacctypeind, s.earningsuifcode, s.eepercentreg, s.employstatuscode, s.erpercentreg, s.extendibleintfileind, s.multiuifcoind, s.othernoopa, s.othernoopn, s.reasonnoncontribcode, s.uifccfilepath, s.uifcocodeend, s.uifcocodestart, s.uifcono, s.uifcoodbc, s.uifcountryind, s.uifeecontribcode, s.uifercontribcode, s.uiffileno, s.uiffileodbc, s.uifgrstaxremuncode, s.uifinterimfilepath, s.uiflimitreg, s.uifmonthlylimit
FROM :"legacy_schema".settings_zaf_uif s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_zaf_uif_company ----
INSERT INTO settings_zaf_uif_company (uif_co_no, contact_email, tax_no, trading_name, uif_no)
SELECT s.uifcono, s.contactemail, s.taxno, s.tradingname, s.uifno
FROM :"legacy_schema".settings_zaf_uif_company s;

-- ---- settings_zaf_uif_file ----
INSERT INTO settings_zaf_uif_file (file_no, contact_email, contact_name, contact_tel_no, creators_name, creators_no, gen_no, medium_size, uif_file_path_name)
SELECT s.fileno, s.contactemail, s.contactname, s.contacttelno, s.creatorsname, s.creatorsno, s.genno, s.mediumsize, s.uiffilepathname
FROM :"legacy_schema".settings_zaf_uif_file s
ON CONFLICT (file_no) DO NOTHING;

-- ---- settings_zaf_uif_file_sort ----
INSERT INTO settings_zaf_uif_file_sort (file_no, ordinal_no, sortopa, sort_op_n, sort_start, sort_end)
SELECT s.fileno, s.ordinalno, s.sortopa, s.sortopn, s.sortstart, s.sortend
FROM :"legacy_schema".settings_zaf_uif_file_sort s
ON CONFLICT (file_no, ordinal_no) DO NOTHING;

-- ---- settings_fund_coida ----
INSERT INTO settings_fund_coida (payroll, co_cost_code_end, co_cost_code_start, director_ind, earns_bal_code, earns_in_kind_bal_code, emp_assess_ind, periods_bal_code, vol_earns_bal_code, vol_e_in_k_bal_code, vol_periods_bal_code)
SELECT s.payroll, s.cocostcodeend, s.cocostcodestart, s.directorind, s.earnsbalcode, s.earnsinkindbalcode, s.empassessind, s.periodsbalcode, s.volearnsbalcode, s.voleinkbalcode, s.volperiodsbalcode
FROM :"legacy_schema".settings_fund_coida s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_zaf_sars_company_values ----
INSERT INTO settings_zaf_sars_company_values (scvcc_value, scvsars_alpha, scvsars_co_no, scvsars_file_no)
SELECT s.scvccvalue, s.scvsarsalpha, s.scvsarscono, s.scvsarsfileno
FROM :"legacy_schema".settings_zaf_sars_company_values s
ON CONFLICT (scvcc_value, scvsars_alpha) DO NOTHING;

-- ---- settings_zaf_sars_company ----
INSERT INTO settings_zaf_sars_company (company_id, ad1_unit, ad2_complex, ad3_street_no, ad4_street_name, ad5_suburb, ad6_town, ad7_post_code, ad8_country_code, cert_prefix, contact_cell_no, contact_email, contact_fax_no, contact_no, contact_person, contact_position, contact_surname, indemnity_ind, file_path_name, certificate_start_no, paye_reference, sdl_reference, sez_code, sic7_code, trade_classification, uif_reference)
SELECT s.company_id, s.ad1_unit, s.ad2_complex, s.ad3_streetno, s.ad4_streetname, s.ad5_suburb, s.ad6_town, s.ad7_postcode, s.ad8_countrycode, s.certprefix, s.contactcellno, s.contactemail, s.contactfaxno, s.contactno, s.contactperson, s.contactposition, s.contactsurname, s.indemnityind, s.filepathname, s.certificatestartno, s.payereference, s.sdlreference, s.sezcode, s.sic7code, s.tradeclassification, s.uifreference
FROM :"legacy_schema".settings_zaf_sars_company s
ON CONFLICT (company_id) DO NOTHING;

-- ---- settings_zaf_sars_file ----
INSERT INTO settings_zaf_sars_file (sars_parm_file_no, addr1, addr2, addr3, addr4, alt_contact_tel_no, contact_name, contact_tel_no, creators_name, creators_no, gen_no, medium_size, postal_code, sars_file_path_name)
SELECT s.sarsparmfileno, s.addr1, s.addr2, s.addr3, s.addr4, s.altcontacttelno, s.contactname, s.contacttelno, s.creatorsname, s.creatorsno, s.genno, s.mediumsize, s.postalcode, s.sarsfilepathname
FROM :"legacy_schema".settings_zaf_sars_file s
ON CONFLICT (sars_parm_file_no) DO NOTHING;

-- ---- settings_zaf_sars_file_sort ----
INSERT INTO settings_zaf_sars_file_sort (sars_parm_file_no, ordinal_no, sort_end, sort_opa, sort_opn, sort_start)
SELECT s.sarsparmfileno, s.ordinalno, s.sortend, s.sortopa, s.sortopn, s.sortstart
FROM :"legacy_schema".settings_zaf_sars_file_sort s
ON CONFLICT (sars_parm_file_no, ordinal_no) DO NOTHING;

-- ---- zaf_sars_print ----
INSERT INTO zaf_sars_print (page_no, line_number, break_value, group_field, group_field_header, group_field_header2, group_field_header3, print_line)
SELECT s.pageno, s.linenumber, s.breakvalue, s.groupfield, s.groupfieldheader, s.groupfieldheader2, s.groupfieldheader3, s.printline
FROM :"legacy_schema".zaf_sars_print s
ON CONFLICT (page_no, line_number) DO NOTHING;

-- ---- zaf_sars_work ----
INSERT INTO zaf_sars_work (employee_id, first_names, initials, irp5_no, selected, surname)
SELECT e.user_id, s.firstnames, s.initials, s.irp5no, s.selected, s.surname
FROM :"legacy_schema".zaf_sars_work s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (employee_id) DO NOTHING;

COMMIT;
\echo 'Done (50_legacy_carry_company.sql):' :tenant_schema '<-' :legacy_schema