-- ===========================================================================
-- 55_legacy_carry_payroll.sql — interim PAYROLL-schema tables
-- GENERATED by tools/generate-carry.js — edit the generator, not this file.
-- Run ONCE PER TENANT after 10_employees.sql (employee ids must exist).
-- Runner variables: :legacy_schema :tenant_schema :payroll_number
--
-- Source identifiers are UNQUOTED LOWERCASE: DataDictionary's ColumnCollection
-- lowercases every table/column name, so that is what the desktop DB contains.
-- CONFIRM: :payroll_number fills the payroll scoping column where the interim table had none (migration_map.legacy_payroll_number).
-- ===========================================================================
\set ON_ERROR_STOP on
BEGIN;
SET search_path TO :"tenant_schema", public;

-- ---- settings_user_tax ----
INSERT INTO settings_user_tax (payroll, cum_tax_ind, default_tax_auth, marginal_basic_tax_code, marginal_rate_code, marginal_tax_code, no_of_periods, no_of_runs, paye_only_ind, resident_ind, tax_authority_country_code, tax_authority_ind, taxed_to_period_code, tax_periods_code, tax_to_date_code, year_end_date, year_end_period, year_start_date, zero_gross_tax_stop_ind)
SELECT s.payroll, s.cumtaxind, s.defaulttaxauth, s.marginalbasictaxcode, s.marginalratecode, s.marginaltaxcode, s.noofperiods, s.noofruns, s.payeonlyind, s.residentind, s.taxauthoritycountrycode, s.taxauthorityind, s.taxedtoperiodcode, s.taxperiodscode, s.taxtodatecode, s.yearenddate, s.yearendperiod, s.yearstartdate, s.zerogrosstaxstopind
FROM :"legacy_schema".settings_user_tax s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_taxcodes ----
INSERT INTO settings_taxcodes (payroll, currency, add_tax_code, add_tax_ytd_code, basic_code, bonus_tax_code, bonus_tax_ytd_code, bonus_ti_ytd_code, currency_code, gi_code, gi_ytd_code, med_aid_code, med_aid_ytd_code, net_code, non_cash_gi_code, non_cash_giytd_code, paye_tax_ytd_code, paye_ti_ytd_code, revised_ti_ytd_code, rf_allowed_code, rf_allowed_ytd_code, rf_code, rf_ytd_code, standard_ti_code, tax_adj_bal_code, tax_adj_code, tax_code, tax_credit_annual_code, tax_credit_periodl_code, tax_ytd_code, ti_code, ti_ytd_code, total_deds_code)
SELECT s.payroll, s.currency, s.addtaxcode, s.addtaxytdcode, s.basiccode, s.bonustaxcode, s.bonustaxytdcode, s.bonustiytdcode, s.currencycode, s.gicode, s.giytdcode, s.medaidcode, s.medaidytdcode, s.netcode, s.noncashgicode, s.noncashgiytdcode, s.payetaxytdcode, s.payetiytdcode, s.revisedtiytdcode, s.rfallowedcode, s.rfallowedytdcode, s.rfcode, s.rfytdcode, s.standardticode, s.taxadjbalcode, s.taxadjcode, s.taxcode, s.taxcreditannualcode, s.taxcreditperiodlcode, s.taxytdcode, s.ticode, s.tiytdcode, s.totaldedscode
FROM :"legacy_schema".settings_taxcodes s
ON CONFLICT (payroll, currency) DO NOTHING;

-- ---- settings_payroll_dates ----
INSERT INTO settings_payroll_dates (payroll, ordinal_no, description, date_d1)
SELECT :payroll_number, s.ordinalno, s.description, s.date_d1
FROM :"legacy_schema".settings_payroll_dates s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_payroll_precision_amounts ----
INSERT INTO settings_payroll_precision_amounts (payroll, ordinal_no, description, amount_r)
SELECT :payroll_number, s.ordinalno, s.description, s.amount_r
FROM :"legacy_schema".settings_payroll_precision_amounts s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- run_history ----
INSERT INTO run_history (run_year, run_period, employee_id, run_date, birth_date, engage_date, discharge_date, employee_code, surname, initials, payroll, cost_code, tax_code, occupation, stop_pay, category, gender, tax_dependants)
SELECT s.runyear, s.runperiod, e.user_id, s.rundate, s.birthdate, s.engagedate, s.dischargedate, s.employeeid, s.surname, s.initials, s.payroll, s.costcode, s.taxcode, s.occupation, s.stoppay, s.category, s.gender, s.taxdependants
FROM :"legacy_schema".run_history s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (run_year, run_period, employee_id) DO NOTHING;

-- ---- run_history_amounts ----
INSERT INTO run_history_amounts (payroll, run_year, run_period, employee_id, ordinal_no, usage_id, code_name, code_type, amount)
SELECT :payroll_number, s.runyear, s.runperiod, e.user_id, s.ordinalno, s.usageid, s.codename, s.codetype, s.amount
FROM :"legacy_schema".run_history_amounts s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (payroll, run_year, run_period, employee_id, ordinal_no, usage_id) DO NOTHING;

-- ---- run_history_alpha ----
INSERT INTO run_history_alpha (payroll, run_year, run_period, employee_id, ordinal_no, reference, ref_name)
SELECT :payroll_number, s.runyear, s.runperiod, e.user_id, s.ordinalno, s.reference, s.refname
FROM :"legacy_schema".run_history_alpha s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (payroll, run_year, run_period, employee_id, ordinal_no) DO NOTHING;

-- ---- run_history_accounts ----
INSERT INTO run_history_accounts (payroll, run_year, run_period, employee_id, ordinal_no, pay_mode, account_type, account_name, account_number, branch_code, source_bank_account, split_pay_code, account_holder_status, sars_bank_account, account_iban, account_currency)
SELECT :payroll_number, s.runyear, s.runperiod, e.user_id, s.ordinalno, s.paymode, s.accounttype, s.accountname, s.accountnumber, s.branchcode, s.sourcebankaccount, s.splitpaycode, s.accountholderstatus, s.sarsbankaccount, s.accountiban, s.accountcurrency
FROM :"legacy_schema".run_history_accounts s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (payroll, run_year, run_period, employee_id, ordinal_no) DO NOTHING;

-- ---- employee_interim ----
INSERT INTO employee_interim (payroll, employee_id, cost_code, user_id)
SELECT :payroll_number, e.user_id, s.costcode, s.user_id
FROM :"legacy_schema".employee_interim s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (payroll, employee_id) DO NOTHING;

-- ---- employee_interim_items ----
INSERT INTO employee_interim_items (payroll, employee_id, ordinal_no, qmf_code)
SELECT :payroll_number, e.user_id, s.ordinalno, s.qmfcode
FROM :"legacy_schema".employee_interim_items s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (payroll, employee_id, ordinal_no) DO NOTHING;

-- ---- settings_auto_ytd ----
INSERT INTO settings_auto_ytd (payroll, ordinal_no, destination_code_a, destination_code_n, source_code_a, source_code_n)
SELECT :payroll_number, s.ordinalno, s.destinationcodea, s.destinationcoden, s.sourcecodea, s.sourcecoden
FROM :"legacy_schema".settings_auto_ytd s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_calculations ----
INSERT INTO settings_calculations (payroll, calc_set, ordinal_no, calc_code, ind_sub, ind_val, op1_a, op1_n, op1_x, op2_a, op2_n, op2_x, op3_a, op3_n, op_code)
SELECT :payroll_number, s.calcset, s.ordinalno, s.calccode, s.indsub, s.indval, s.op1a, s.op1n, s.op1x, s.op2a, s.op2n, s.op2x, s.op3a, s.op3n, s.opcode
FROM :"legacy_schema".settings_calculations s
ON CONFLICT (payroll, calc_set, ordinal_no) DO NOTHING;

-- ---- settings_calendar ----
INSERT INTO settings_calendar (payroll, ordinal_no, clear_concostf_ind, clear_conf_ind, days_in_period, pay_period_from, pay_period_to, run_date, run_done_ind, run_in_month, runs_in_month, tax_month, tax_period)
SELECT :payroll_number, s.ordinalno, s.clearconcostfind, s.clearconfind, s.daysinperiod, s.payperiodfrom, s.payperiodto, s.rundate, s.rundoneind, s.runinmonth, s.runsinmonth, s.taxmonth, s.taxperiod
FROM :"legacy_schema".settings_calendar s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_costing_codes ----
INSERT INTO settings_costing_codes (payroll, ordinal_no, costing_code, costing_cost_code, costing_method)
SELECT :payroll_number, s.ordinalno, s.costingcode, s.costingcostcode, s.costingmethod
FROM :"legacy_schema".settings_costing_codes s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_exceptions ----
INSERT INTO settings_exceptions (payroll, ordinal_no, mess)
SELECT s.payroll, s.ordinalno, s.mess
FROM :"legacy_schema".settings_exceptions s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_holidays ----
INSERT INTO settings_holidays (payroll, ordinal_no, holiday_date, holiday_type)
SELECT :payroll_number, s.ordinalno, s.holidaydate, s.holidaytype
FROM :"legacy_schema".settings_holidays s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_rolling_history ----
INSERT INTO settings_rolling_history (payroll, ordinal_no, no_of_columns, no_of_rows, start_qmf_code)
SELECT :payroll_number, s.ordinalno, s.noofcolumns, s.noofrows, s.startqmfcode
FROM :"legacy_schema".settings_rolling_history s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_rolling_hist_fields ----
INSERT INTO settings_rolling_hist_fields (payroll, ordinal_no, date_table, col_fieldopa, col_field_op_n)
SELECT :payroll_number, s.ordinalno, s.datetable, s.colfieldopa, s.colfieldopn
FROM :"legacy_schema".settings_rolling_hist_fields s
ON CONFLICT (payroll, ordinal_no, date_table) DO NOTHING;

-- ---- settings_special_runs ----
INSERT INTO settings_special_runs (payroll, special_run_no, include3rd_party_trans, include_batch_mastf, include_batch_trans, include_delay_trans, include_man_pays, include_other_trans, include_perm_trans, reversal_iter, spec_run_name, zero_runf_flag)
SELECT :payroll_number, s.specialrunno, s.include3rdpartytrans, s.includebatchmastf, s.includebatchtrans, s.includedelaytrans, s.includemanpays, s.includeothertrans, s.includepermtrans, s.reversaliter, s.specrunname, s.zerorunfflag
FROM :"legacy_schema".settings_special_runs s
ON CONFLICT (payroll, special_run_no) DO NOTHING;

-- ---- settings_table_access ----
INSERT INTO settings_table_access (payroll, ordinal_no, end_col, end_row, in1_a, in1_n, in2_a, in2_n, in3_a, in3_n, out1_a, out1_n, out2_a, out2_n, out3_a, out3_n, start_col, start_row, table_color, table_name, table_type)
SELECT :payroll_number, s.ordinalno, s.endcol, s.endrow, s.in1a, s.in1n, s.in2a, s.in2n, s.in3a, s.in3n, s.out1a, s.out1n, s.out2a, s.out2n, s.out3a, s.out3n, s.startcol, s.startrow, s.tablecolor, s.tablename, s.tabletype
FROM :"legacy_schema".settings_table_access s
ON CONFLICT (payroll, ordinal_no) DO NOTHING;

-- ---- settings_table_values ----
INSERT INTO settings_table_values (payroll, ordinal_no, row_no, item)
SELECT :payroll_number, s.ordinalno, s.row, s.item
FROM :"legacy_schema".settings_table_values s
ON CONFLICT (payroll, ordinal_no, row_no) DO NOTHING;

-- ---- pay_run_messages ----
INSERT INTO pay_run_messages (payroll, id, employee_id, amount, class_no, code, cost_code, disch_ind, initials, message_field, message_type, op1_a, op1_amount, op1_n, op2_a, op2_amount, op2_n, replace_ind, surname, sys_code)
SELECT :payroll_number, s.autonumber, e.user_id, s.amount, s.classno, s.code, s.costcode, s.dischind, s.initials, s.messagefield, s.messagetype, s.op1a, s.op1amount, s.op1n, s.op2a, s.op2amount, s.op2n, s.replaceind, s.surname, s.syscode
FROM :"legacy_schema".pay_run_messages s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('pay_run_messages', 'id'), (SELECT COALESCE(MAX(id), 0) + 1 FROM pay_run_messages), false);

-- ---- pay_run_tax_audit ----
INSERT INTO pay_run_tax_audit (payroll, id, break_key, employee_id, line_nr, break_key_descr, page_nr, print_line, report_section, run_date)
SELECT :payroll_number, s.autonumber, s.breakkey, e.user_id, s.linenr, s.breakkeydescr, s.pagenr, s.printline, s.reportsection, s.rundate
FROM :"legacy_schema".pay_run_tax_audit s
JOIN employees e ON e.id = 'emp-' || s.employeeno::text
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('pay_run_tax_audit', 'id'), (SELECT COALESCE(MAX(id), 0) + 1 FROM pay_run_tax_audit), false);

-- ---- ratef ----
INSERT INTO ratef (payroll, id, code, date_value, cost_code, description, effective_date, rate_value)
SELECT :payroll_number, s.autonumber, s.code, s.datevalue, s.costcode, s.description, s.effectivedate, s.ratevalue
FROM :"legacy_schema".ratef s
ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('ratef', 'id'), (SELECT COALESCE(MAX(id), 0) + 1 FROM ratef), false);

-- ---- settings_taxcodes_cod_congo ----
INSERT INTO settings_taxcodes_cod_congo (payroll, currency, currency_code, drctd_rebate_val_code, drctof_income_code, drctof_income_tax)
SELECT s.payroll, s.currency, s.currencycode, s.drctdrebatevalcode, s.drctofincomecode, s.drctofincometax
FROM :"legacy_schema".settings_taxcodes_cod_congo s
ON CONFLICT (payroll, currency) DO NOTHING;

-- ---- settings_taxcodes_gha_ghana ----
INSERT INTO settings_taxcodes_gha_ghana (payroll, currency, currency_code, ghana_ot_basic_pay, ghana_ot_total_inc, ghana_overtime_code, ghana_overtime_tax_code)
SELECT s.payroll, s.currency, s.currencycode, s.ghanaotbasicpay, s.ghanaottotalinc, s.ghanaovertimecode, s.ghanaovertimetaxcode
FROM :"legacy_schema".settings_taxcodes_gha_ghana s
ON CONFLICT (payroll, currency) DO NOTHING;

-- ---- settings_taxcodes_ken_kenya ----
INSERT INTO settings_taxcodes_ken_kenya (payroll, currency, currency_code, kenya_elg_insurance_prem)
SELECT s.payroll, s.currency, s.currencycode, s.kenyaelginsuranceprem
FROM :"legacy_schema".settings_taxcodes_ken_kenya s
ON CONFLICT (payroll, currency) DO NOTHING;

-- ---- settings_user_mli_mali ----
INSERT INTO settings_user_mli_mali (payroll, mali_adult_dis_tax_dep_code)
SELECT s.payroll, s.maliadultdistaxdepcode
FROM :"legacy_schema".settings_user_mli_mali s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_taxcodes_mus_mauritius ----
INSERT INTO settings_taxcodes_mus_mauritius (payroll, currency, currency_code, mau_allowed_edfytd, mau_all_tertiaty_edfytd, mau_annual_edf_amt_adj_code, mau_annual_edf_code, mau_edf_adj_applied_ytd, mau_edf_adjusted_ti, mau_solidarity_levy_code, mau_solidarity_levy_ytd_code, mau_tertiary_tax_dep_code, mau_total_period_edf)
SELECT s.payroll, s.currency, s.currencycode, s.mauallowededfytd, s.maualltertiatyedfytd, s.mauannualedfamtadjcode, s.mauannualedfcode, s.mauedfadjappliedytd, s.mauedfadjustedti, s.mausolidaritylevycode, s.mausolidaritylevyytdcode, s.mautertiarytaxdepcode, s.mautotalperiodedf
FROM :"legacy_schema".settings_taxcodes_mus_mauritius s
ON CONFLICT (payroll, currency) DO NOTHING;

-- ---- settings_user_nam_namibia ----
INSERT INTO settings_user_nam_namibia (payroll, namib_tax_registration_ind)
SELECT s.payroll, s.namibtaxregistrationind
FROM :"legacy_schema".settings_user_nam_namibia s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_taxcodes_nam_namibia ----
INSERT INTO settings_taxcodes_nam_namibia (payroll, currency, currency_code, namib_edpol_code, namib_edpol_ytd_code, namib_prov_code, namib_prov_ytd_code)
SELECT s.payroll, s.currency, s.currencycode, s.namibedpolcode, s.namibedpolytdcode, s.namibprovcode, s.namibprovytdcode
FROM :"legacy_schema".settings_taxcodes_nam_namibia s
ON CONFLICT (payroll, currency) DO NOTHING;

-- ---- settings_taxcodes_swz_eswatini ----
INSERT INTO settings_taxcodes_swz_eswatini (payroll, currency, currency_code, swazi_appr_funds_code, swazi_appr_funds_ytd_code, swazi_graded_tax_ytd_code, swazi_prov_code, swazi_prov_ytd_code, swazi_total_tax_rebate_code)
SELECT s.payroll, s.currency, s.currencycode, s.swaziapprfundscode, s.swaziapprfundsytdcode, s.swazigradedtaxytdcode, s.swaziprovcode, s.swaziprovytdcode, s.swazitotaltaxrebatecode
FROM :"legacy_schema".settings_taxcodes_swz_eswatini s
ON CONFLICT (payroll, currency) DO NOTHING;

-- ---- settings_user_zaf_southafrica ----
INSERT INTO settings_user_zaf_southafrica (payroll, eti_claim_code, eti_hours_code, eti_ind_no, eti_monthly_min_wage_code, eti_month_to_date_gross_code, eti_wage_paid_code, med_aid_tax_cr_all_ytd_code, med_aid_tax_cr_ytd_code, skills_leviable_amt_code, skills_levy_code, skills_levy_percent_reg)
SELECT s.payroll, s.eticlaimcode, s.etihourscode, s.etiindno, s.etimonthlyminwagecode, s.etimonthtodategrosscode, s.etiwagepaidcode, s.medaidtaxcrallytdcode, s.medaidtaxcrytdcode, s.skillsleviableamtcode, s.skillslevycode, s.skillslevypercentreg
FROM :"legacy_schema".settings_user_zaf_southafrica s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_apso_tax ----
INSERT INTO settings_apso_tax (payroll, apso_ind, period_code_end, period_code_start)
SELECT s.payroll, s.apsoind, s.periodcodeend, s.periodcodestart
FROM :"legacy_schema".settings_apso_tax s
ON CONFLICT (payroll) DO NOTHING;

-- ---- settings_taxcodes_zwe_zimbabwe ----
INSERT INTO settings_taxcodes_zwe_zimbabwe (payroll, currency, currency_code, zim_aids_levy_code, zim_aids_levy_ytd_code, zim_bonus_code, zim_bonus_tax_free_max_code, zim_bonus_ytd_code, zim_blind_ann_tax_cr_code, zim_blind_per_tax_cr_code, zim_blind_used_tax_cr_code, zim_dis_ann_tax_cr_code, zim_dis_per_tax_cr_code, zim_dis_used_tax_cr_code, zim_eld_ann_tax_cr_code, zim_eld_per_tax_cr_code, zim_eld_used_tax_cr_code, zim_med_exp_code, zim_med_exp_ytd_code, zim_pens_allowed_code, zim_prev_yr_bonus_code, zim_sev_pay_code, zim_sev_pay_non_txd_code, zim_sev_pay_taxed_code, zim_sev_pay_ytd_code, zim_tax_credit_code, zim_tax_credit_ret_code, zim_tax_credit_used_ytd_code, zim_year_start_period)
SELECT s.payroll, s.currency, s.currencycode, s.zimaidslevycode, s.zimaidslevyytdcode, s.zimbonuscode, s.zimbonustaxfreemaxcode, s.zimbonusytdcode, s.zimblindanntaxcrcode, s.zimblindpertaxcrcode, s.zimblindusedtaxcrcode, s.zimdisanntaxcrcode, s.zimdispertaxcrcode, s.zimdisusedtaxcrcode, s.zimeldanntaxcrcode, s.zimeldpertaxcrcode, s.zimeldusedtaxcrcode, s.zimmedexpcode, s.zimmedexpytdcode, s.zimpensallowedcode, s.zimprevyrbonuscode, s.zimsevpaycode, s.zimsevpaynontxdcode, s.zimsevpaytaxedcode, s.zimsevpayytdcode, s.zimtaxcreditcode, s.zimtaxcreditretcode, s.zimtaxcreditusedytdcode, s.zimyearstartperiod
FROM :"legacy_schema".settings_taxcodes_zwe_zimbabwe s
ON CONFLICT (payroll, currency) DO NOTHING;

COMMIT;
\echo 'Done (55_legacy_carry_payroll.sql):' :tenant_schema '<-' :legacy_schema